version: '3'

volumes:
  data:
  rubyricdb:

services:
  grader:
    image: apluslms/run-mooc-grader:1.19
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aplus:/tmp/aplus
      - .:/srv/courses/default:ro
    ports:
      - "8080:8080"
  plus:
    image: apluslms/run-aplus-front:1.19
    environment:
      APLUS_ENABLE_DJANGO_DEBUG_TOOLBAR: 'false'
    volumes:
      - data:/data
    ports:
      - "8000:8000"
    depends_on:
      - grader
      - acos
      - rubyric
  jutut:
    image: apluslms/run-mooc-jutut:2.5
    volumes:
      - data:/data
    ports:
      - "8082:8082"
  acos:
    image: apluslms/run-acos-server
    user: $USER_ID:$USER_GID
    ports:
      - "3000:3000"
    #volumes:
    #  - ./_data/acos/:/var/log/acos
  radar:
    image: apluslms/run-radar
    ports:
      - "8001:8001"
      # Django debug
      - "5678:5678"
      # Celery debug
      - "5679:5679"
      # Flower (celery dashboard)
      - "5555:5555"
    depends_on:
      - plus
      - grader
    volumes:
      - data:/data
  rubyric:
    image: apluslms/run-rubyric
    volumes:
      - data:/data
    ports:
      - "8091:8091"
    depends_on:
      - rubyricdb
  rubyricdb:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_USER: rubyric
      POSTGRES_PASSWORD: rubyric
      POSTGRES_DB: rubyric
    volumes:
      - rubyricdb:/var/lib/postgresql/data
