version: '3'

services:
  grader:
    image: apluslms/run-mooc-grader
    user: $USER_ID:$DOCKER_GID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aplus:/tmp/aplus
      - .:/srv/courses/default:ro
      - ./_data/:/srv/data
    ports:
      - "8080:8080"
  plus:
    image: apluslms/run-aplus-front
    user: $USER_ID:$USER_GID
    volumes:
      - ./_data/:/srv/data
    ports:
      - "8000:8000"
    depends_on:
      - grader
  acos:
    image: apluslms/run-acos-server
    user: $USER_ID:$USER_GID
    ports:
      - "3000:3000"
    # depends_on is only used to control the start-up order of the containers so that
    # the ACOS container would more likely be assigned the IP address hardcoded into the course configuration
    depends_on:
      - plus
      - grader

