---
title: Hello Scala!
description: An example of grading with Scala code
instructions: |
    <p>
        In this exercise you must implement <code>object HelloScala</code>
        in <code>package hello</code>. The object must have a method named
        <var>hello</var> that returns a String "<samp>Hello Scala!</samp>".
    </p>
    <p>
        The result may be tested with REPL typing<br />
        <kbd>import hello.HelloScala; HelloScala.hello</kbd>
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: HelloScala.scala

container:
  image: apluslms/grade-scala:2.12-3.0
  mount: exercises/hello_scala
  cmd: /exercise/run.sh
