---
title: Hello Python!
description: A simple grading example with Python code
instructions: |
    <p>
        In this exercise you must implement a function <var>hello</var>
        that returns a string "<samp>Hello Python!</samp>".
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: functions.py

container:
  image: apluslms/grade-python:3.7-3.2.3-3.0
  mount: exercises/hello_python
  cmd: /exercise/run.sh
