---
title: Template extension
description: Extending the default feedback template
instructions: |
    <p>
        This exercise shows how the default html feedback can be extended with a template.
        Any Python file can be submitted.
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: file.py

container:
  image: apluslms/grade-python:3.7-3.5-3.4
  mount: exercises/template_extension
  cmd: graderutils
